config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "book/list"
  get "book/new"
  post "book/create"
  patch "book/update"
  get "book/list"
  get "book/show"
  get "book/edit"
  get "book/delete"
  get "book/update"
  get "book/show_subjects"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :subject
    validates_presence_of :title
    validates_numericality_of :price, :message=>"Error Message"
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_controller.rb
class BookController < ApplicationController
    def list
        @books = Book.all
     end
  
     def show
        @book = Book.find(params[:id])
     end
    
     def new
        @book = Book.new
        @subjects = Subject.all
     end
  
     def book_params
        params.require(:books).permit(:title, :price, :subject_id, :description)
     end
  
     def create
        @book = Book.new(book_params)
  
        if @book.save
           redirect_to :action => 'list'
        else
           @subjects = Subject.all
           render :action => 'new'
        end
     end
     
     def edit
        @book = Book.find(params[:id])
        @subjects = Subject.all
     end
     
     def book_param
        params.require(:book).permit(:title, :price, :subject_id, :description)
     end
     
     def update
        @book = Book.find(params[:id])
        
        #if @book.update_attributes(book_param)
        if @book.update(book_param)
           redirect_to :action => 'show', :id => @book
        else
           @subjects = Subject.all
           render :action => 'edit'
        end
     end
     
     def delete
        Book.find(params[:id]).destroy
        redirect_to :action => 'list'
     end
     
     def show_subjects
        @subject = Subject.find(params[:id])
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/book/edit.html.erb
<h1>Edit Book Detail</h1>

<%= form_for @book, :url =>{:action => "update", :id => @book} do |f| %>
<p>Title: <%= f.text_field "title" %></p>
<p>Price: <%= f.text_field "price" %></p>
<p>Subject: <%= f.collection_select :subject_id, Subject.all, :id, :name %></p>
<p>Description<br>
<%= f.text_area "description" %></p>
<%= f.submit "Save changes" %>
<% end %>

<%= link_to "Back", {:action => "list" } %>

app/views/book/list.html.erb
<p><%= link_to "Add new Book", {:action => "new"} %></p>
<% if @books.blank? %>
    <p>There are not any books currently in the system.</p>
<% else %>
    <ul id="subjects">
        <% Subject.all.each do |c| %>
            <li><%= link_to c.name, book_show_subjects_path(id: c.id) %></li>
        <% end %>
    </ul>
    <p>These are the current books in our system</p>
    <ul id="books">
        <% @books.each do |c| %>
            <li>
                <%#= link_to c.title, {:action => "show", :id=> c.id} %>
                <%= link_to c.title, book_show_path(id: c.id) %>
                <b><%= link_to "Edit", book_edit_path(id: c.id) %></b>
                <b><%= link_to "Delete", {:action => 'delete', :id => c.id},
      :confirm => "Are you sure you want to delete this item?" %></b>
            </li>
        <% end %>
    </ul>
<% end %>

app/views/book/new.html.erb
<h1>Add new book</h1>

<%= form_tag :action => 'create' do %>
<p><label for = "book_title">Title</label>:

<%= text_field 'books', 'title' %></p>
<p><label for = "book_price">Price</label>:

<%= text_field 'books', 'price' %></p>
<p><label for = "book_subject_id">Subject</label>:

<%= collection_select(:books, :subject_id, @subjects, :id, :name, prompt: true) %></p>
<p><label for = "book_description">Description</label><br/>

<%= text_area 'books', 'description' %></p>
<%= submit_tag "Create" %>

<% end -%>
<%= link_to 'Back', {:action => 'list'} %>

app/views/book/show.html.erb
<h1><%= @book.title %></h1>
<p>
    <strong>Price: </strong><%= @book.price %><br>
    <strong>Subject: </strong><%= link_to @book.subject.name, show_subjects_path(id: @book.subject.id) %><br>
    <strong>Created Date: </strong><%= @book.created_at %><br>
</p>
<p><%= @book.description %></p>
<hr>
<%= link_to "Back", book_list_path %>
<%#= link_to "Locations", locations_path, class: "nav-link" %>

app/views/book/show_subjects.html.erb
<h1><%= @subject.name %></h1>
<ul>
    <%= @subject.books.each do |c| %>
        <li><%= link_to c.title, book_show_subjects_path(id: c.id)%></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>Library Info System</title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="library">
    <div id="container">
      <div id="header">
        <h1>Library Info System</h1>
        <h3>Library powered by Ruby on Rails</h3>
      </div>
      <div id="content">
        <%= yield %>
      </div>
      <div id="sidebar"></div>
    </div>
  </body>
</html>